#!/bin/bash
set -eux

# Sets up systemd-networkd
mkosi-chroot \
        dnf install -y dnf-plugins-core

mkosi-chroot \
        dnf copr enable -y prymar56/virt10-xen alma-kitten+epel-10-x86_64

mkosi-chroot \
        dnf install -y systemd-networkd

# Creates the qemu-system-x86_64 executable from the Rocky's qemu binary.
mkosi-chroot \
	ln -sf  /usr/libexec/qemu-kvm /usr/bin/qemu-system-x86_64

# Installs emoji module using pip
mkosi-chroot \
	pip3 install  emoji
